Fixes the errors while running the project for Lumen
Napp/xray-laravel pull request #51
Opened 2024-04-03 10:54 UTC by SachinBahukhandi

Fixes: #50

2024-04-10 18:54 UTC, SachinBahukhandi commented
Hey @viezel any plans on reviewing this, please?
It could be very much helpful for us like devs in using your package for lumen. Thanks!

2024-04-11 06:33 UTC, viezel requested changes
Cannot accept this

2024-04-11 06:33 UTC, viezel commented on src/Collectors/FrameworkCollector.php
> +        if($this->app instanceof \Laravel\Lumen\Application){
You cannot refer to this->app due to you just deleted the proptery

2024-04-11 06:33 UTC, viezel commented on src/Collectors/FrameworkCollector.php
> +        }
How did you test this logic? It seems incorrect as you have two endsection and incorrect type.

2024-04-11 06:33 UTC, viezel commented on src/Collectors/EventsCollector.php
> -    protected $app;
Why remove this?

2024-07-03 10:47 UTC, closed without merging